### ISSUE TITLE
challenge 010: staging

### ISSUE THREAD

**Issue by RouvenGonzalez** [software-developer-org/sandbox#10]
getting started

**Comment by RouvenGonzalez** [comment]
@RagipGashi  please review my work :)

**Comment by RagipGashi** [comment]
@RouvenGonzalez, I've done it. It looks pretty good. All what I could notice, is some fixed files, and it has happened many times by me too. The other part I find really a good job. Congrats.

**Comment by RagipGashi** [comment]
@RouvenGonzalez, at the commit with the number 0482c0b, you have put some notes that has helped me indeed. Thank you.

**Comment by RouvenGonzalez** [comment]
Thx :D 
have you found some bugs or somthing i should fix ?

**Comment by RagipGashi** [comment]
No, I haven't found anything like a bag or something that should be fixed.
It looks like a clear job. Congrats!

**Comment by RouvenGonzalez** [comment]
All right thx closing this now.
