### ISSUE TITLE
challenge 010: new feature 

### ISSUE THREAD

**Issue by RagipGashi** [software-developer-org/sandbox#11]
my first feature

**Comment by taitruong** [comment]
Title "git started: new feature" ist nicht korrekt. Sollte "challenge 010: new feature" heißen. Ist ein "Bug" im ersten Exercise. Sollte gefixed werden. Bitte Notiz in eurem Branch machen. Danke, Tai

**Comment by taitruong** [comment]
Ich habe es mir angeschaut. Die Challenge ist nicht vollständig. Zum Beispiel ist das File leer. Ich sehe keine Markdown styles im File. Nichts! Bitte die Challenge **genau** lesen und **exakt** durcharbeiten.
