### ISSUE TITLE
challenge010: new feature

### ISSUE THREAD

**Issue by RouvenGonzalez** [software-developer-org/sandbox#8]
my first feature

**Comment by taitruong** [comment]
Title "git started: new feature" ist nicht korrekt. Sollte "challenge 010: new feature" heißen. Ist ein "Bug" im ersten Exercise. Sollte gefixed werden. Bitte Notiz in eurem Branch machen. Danke, Tai

**Comment by RouvenGonzalez** [comment]
beides erledigt
